#include "Localization.h"

int g_lang = LANG_EN;

const char* g_strings[2][S_COUNT] = {
    // English
    {
        "Loading", "MENU", "  Protection", "  Detections", "  Logs",
        "LOLBin Protection", "Online", "Offline",
        "CONTROLS", "Enable Protection", "Auto-scroll Logs",
        "Protection started", "Protection stopped",
        "STATUS", "Driver", "Connected", "Error",
        "Active", "Inactive", "%d found", "RULES", "Loaded",
        "Ready", "Loading...",
        "LoLScan monitors process creation and blocks known Living-off-the-Land Binary abuse patterns via a kernel-mode driver.",
        "%d detections", "Time", "Command", "Copy",
        "%d entries", "v1.0  |  %d rules",
        "Application loaded", "Connected to driver successfully",
        "Loading %d rules...", "All rules loaded successfully",
        "Error connecting to driver",
        "Show", "Exit",
        "Clear",
        "Threat Blocked",
        "  Settings",
        "STARTUP",
        "Start with Windows",
        "Creates a Task Scheduler entry that starts LoLScan at sign-in.",
        "Task status",
        "Enabled",
        "Disabled",
    },
    // Russian
    {
        u8"Загрузка",
        u8"МЕНЮ",
        u8"  Защита",
        u8"  Обнаружения",
        u8"  Логи",
        u8"Защита от LOLBin",
        u8"Онлайн",
        u8"Оффлайн",
        u8"УПРАВЛЕНИЕ",
        u8"Включить защиту",
        u8"Автопрокрутка логов",
        u8"Защита включена",
        u8"Защита отключена",
        u8"СТАТУС",
        u8"Драйвер",
        u8"Подключен",
        u8"Ошибка",
        u8"Активна",
        u8"Неактивна",
        u8"%d найд.",
        u8"ПРАВИЛА",
        u8"Загружено",
        u8"Готово",
        u8"Загрузка...",
        u8"LoLScan отслеживает создание процессов и блокирует известные паттерны LOLBin через драйвер ядра.",
        u8"%d обнаруж.",
        u8"Время",
        u8"Команда",
        u8"Копировать",
        u8"%d записей",
        u8"v1.0  |  %d правил",
        u8"Приложение загружено",
        u8"Подключение к драйверу успешно",
        u8"Загрузка %d правил...",
        u8"Все правила загружены",
        u8"Ошибка подключения к драйверу",
        u8"Показать",
        u8"Выход",
        u8"Очистить",
        u8"Угроза заблокирована",
        u8"  Настройки",
        u8"АВТОЗАПУСК",
        u8"Запускать с Windows",
        u8"Создает задачу в Планировщике заданий, которая запускает LoLScan при входе в систему.",
        u8"Статус задачи",
        u8"Включено",
        u8"Выключено",
    },
};
